### ISSUE TITLE
autocomplete

### ISSUE THREAD

**Issue by slachtar** [goldim/vscode-qx6-snippets#1]
I installed the qx6-snippets in vscode, what are the other options provided beside construct...
It will be great if it supports autocompletion.
Thank you for the tool

**Comment by goldim** [comment]
@slachtar thank you very much for the feedback. All autocompletion snippets of this extension are listed in snippets/javascript.js file. Now I know that I have to write them in readme file as documentation. Will do it as soon as possible. Btw I added  qooxdoo autocompletion instructions which I usually use and there are some others which I missed . Just let me now or you could make PR adding them in snippets/javascript.js.

**Comment by goldim** [comment]
@slachtar added list of snippet descriptions in documentation (readme) and some extra snippets. Published v0.1.0 on marketplace too. I thought about autocompletion you said again. Is it autocompletion of user methods, classes etc you mean? If yes then there is a place for another extension for this purpose. It probably would be more difficult to create this one.

**Comment by slachtar** [comment]
Yes I'm talking about autocomplete for classes, methods, etc. It's very helpfull especially for new developers, some developers are still using old SPKET editor just because it has the autocomplete feature.
Thank you again for your effort
